{{! This file is processed with handlebars. The tag helper will return the provided string in double braces}}
version: '2'
template:
  name: Continuous Delivery Toolchain
  description: "This toolchain includes tools to develop and deploy your app. Depending on your app, when you create the toolchain, the GitHub repository will either be empty or will contain source code from your app.\n\nThis toolchain uses tools that are part of the Continuous Delivery service. If an instance of that service isn't already in your organization, when you click **Create**, it is automatically added at no cost to you. For more information and terms, see the [IBM Cloud catalog](/catalog/services/continuous-delivery/).\n\nTo get started, click **Create**."
  required:
    - repo
    - build

toolchain:
  name: {{name}}

services:
  # Github repos
  repo:
    service_id: hostedgit
    parameters:
      repo_url: "{{tag '#zip_url'}}{{tag 'zip_url'}}{{tag '/zip_url'}}{{tag '^zip_url'}}{{tag 'repository'}}{{tag '/zip_url'}}"
      repo_name: "{{tag 'toolchain.name'}}"
      type: {{repoType}}
      has_issues: true
      enable_traceability: true

  # Pipelines
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: "{{tag 'name'}}"
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          CF_APP: "{{tag 'form.pipeline.parameters.app-name'}}"
          API_KEY: "{{tag 'form.pipeline.parameters.api-key'}}"
          {{#has deployment.type 'Kube'}}
          CHART_NAME: "{{tag 'form.pipeline.parameters.chart-name'}}"
          KUBE_CLUSTER_NAME: "{{tag 'form.pipeline.parameters.kube-cluster-name'}}"
          CLUSTER_NAMESPACE: "{{tag 'form.pipeline.parameters.cluster-namespace'}}"
          IMAGE_REGISTRY_TOKEN: "{{tag 'form.pipeline.parameters.image-registry-token'}}"
          REGISTRY_NAMESPACE: "{{tag 'form.pipeline.parameters.registry-namespace'}}"
          {{/has}}
          {{#has deployment.type 'CF'}}
          CF_SPACE: "{{tag 'form.pipeline.parameters.dev-space'}}"
          CF_ORGANIZATION: "{{tag 'form.pipeline.parameters.dev-organization'}}"
          {{/has}}
          {{#has deployment.type 'VSI'}}
          PUBLIC_KEY: "{{form.pipeline.parameters.public-key}}"
          PRIVATE_KEY: "{{form.pipeline.parameters.private-key}}"
          TF_VAR_ibm_sl_username: "{{form.pipeline.parameters.softlayer-username}}"
          TF_VAR_ibm_sl_api_key: "{{form.pipeline.parameters.softlayer-api-key}}"
          GITLAB_USER: "{{form.pipeline.parameters.gitlab-user}}"
          GITLAB_ACCESS_TOKEN: "{{form.pipeline.parameters.gitlab-access-token}}"
          {{/has}}
          REGION_ID: "{{tag 'form.pipeline.parameters.dev-region'}}"
        execute: true

  #Web IDE
  webide:
    service_id: orion

#Deployment
form:
  pipeline:
    schema:
      $ref: deploy.json
    parameters:
      app-name: {{name}}
      dev-region: "{{region}}"
      api-key: "{{tag 'api-key'}}"
      {{#has deployment.type 'Kube'}}
      chart-name: {{deployment.chartName}}
      kube-cluster-name: {{deployment.kubeClusterName}}
      cluster-namespace: {{deployment.kubeClusterNamespace}}
      image-pull-secret-name: "{{tag 'image-pull-secret-name'}}"
      image-registry-token: "{{tag 'image-registry-token'}}"
      registry-namespace: {{deployment.imageRegistryNamespace}}
      {{/has}}
      {{#has deployment.type 'CF'}}
      dev-space: "{{space}}"
      dev-organization: "{{org}}"
      {{/has}}
      {{#has deployment.type 'VSI'}}
      public-key: "{{public-key}}"
      private-key: "{{private-key}}"
      softlayer-username: "{{softlayer-username}}"
      softlayer-api-key: "{{softlayer-api-key}}"
      gitlab-user: "{{gitlab-user}}"
      gitlab-access-token: "{{gitlab-access-token}}"
      {{/has}}

