apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{tag '  .Chart.Name '}}-deployment"
  labels:
    chart: '{{tag ' .Chart.Name '}}-{{tag ' .Chart.Version | replace "+" "_" '}}'
spec:
  replicas: {{tag ' .Values.replicaCount '}}
  revisionHistoryLimit: {{tag ' .Values.revisionHistoryLimit '}}
  template:
    metadata:
      labels:
        app: "{{tag '  .Chart.Name '}}-selector"
        version: "current"
    spec:
      containers:
      - name: "{{tag '  .Chart.Name  '}}"
        image: "{{tag ' .Values.image.repository '}}:{{tag ' .Values.image.tag '}}"
        imagePullPolicy: {{tag ' .Values.image.pullPolicy '}}
{{tag ' if .Values.istio.enabled '}}
{{tag ' else '}}
        readinessProbe:
          httpGet:
          {{! healthEndpoint is configured in the index.js and is different for basicweb}}
          {{#has language 'java'}}
            path: /{{#if healthEndpoint}}{{healthEndpoint}}{{else}}health{{/if}}
            port: 9080
          {{/has}}
          {{#has language 'spring'}}
            path: /{{#if healthEndpoint}}{{healthEndpoint}}{{else}}health{{/if}}
            port: 8080
          {{/has}}
          initialDelaySeconds: 20
{{tag ' end '}}
        resources:
          requests:
            cpu: "{{tag ' .Values.image.resources.requests.cpu '}}"
            memory: "{{tag ' .Values.image.resources.requests.memory '}}"
        env:
          - name: PORT
            value: "{{tag ' .Values.service.servicePort '}}"
          - name: APPLICATION_NAME
            value: "{{tag ' .Release.Name '}}"
          {{#has services 'mongodb'}}
          - name: MONGO_URL
            value: {{tag ' .Values.services.mongo.url '}}
          - name: MONGO_DB_NAME
            value: {{tag ' .Values.services.mongo.name '}}
          {{/has}}
