# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: {{#toLowerCase applicationName}}{{/toLowerCase}}
  tag: v1.0.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
service:
  name: Node
  type: NodePort
  servicePort: {{servicePorts.http}}
{{#if servicePorts.https}}
  servicePortHttps: {{servicePorts.https}}
{{/if}}
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50
{{#storageDeploys.env}}
services:
{{/storageDeploys.env}}
{{#has storages 'mongo'}}
  mongo:
     url: mongo
     name: comments
     env: production
{{/has}}