{{tag ' if .Values.hpa.enabled '}}
apiVersion: autoscaling/v2alpha1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{tag ' .Chart.Name ' }}-hpa-policy"
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: "{{tag ' .Chart.Name ' }}-deployment"
  minReplicas: {{tag ' .Values.hpa.minReplicas '}}
  maxReplicas: {{tag ' .Values.hpa.maxReplicas '}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{tag ' .Values.hpa.metrics.cpu.targetAverageUtilization '}}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{tag ' .Values.hpa.metrics.memory.targetAverageUtilization '}}
{{tag ' end '}}