---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: {{#toLowerCase applicationName}}{{/toLowerCase}}
spec:
  template:
    spec:
      containers:
        - image: REGISTRY_URL/{{ registryNamespace }}/{{#toLowerCase applicationName}}{{/toLowerCase}}:BUILD_NUMBER
          ports:
            - containerPort: {{ servicePorts.http }}
