---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: {{ applicationName }}
  namespace: {{ kubeClusterNamespace }}
spec:
  template:
    spec:
      containers:
        - image: {{ repositoryURL }}{{ applicationName }}
          ports:
            - containerPort: {{ servicePorts.http }}
